x = int(input("please an integer number: "))
y = int(input("please an integer number again: "))
z = int(input("please an integer number again: "))
t = int(input("please an integer number again: "))
w = int(input("please an integer number again: "))
my_list = []
my_list.append(x)
my_list.append(y)
my_list.append(z)
my_list.append(t)
my_list.append(w)
my_list.sort()
print(my_list[-1])